#!/bin/bash

thebranch="$1"

# http://gun.io/blog/how-to-github-fork-branch-and-pull-request/

# if you haven't added an upsteam yet:
# git remote add --track master upstream git://github.com/rapid7/metasploit-framework.git

# get the current branch
function git_branch {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

orig_branch=git_branch

# switch to the branch
git checkout $thebranch
# abort the whole thing if git checkout fails
if [[ $? -ne 0 ]];then echo "Could not checkout the branch:$thebranch";fi

# get the latest code
git fetch upstream

# merge it with your local repo, currently active branch
git merge upstream/master

# now you should consider git push to remote
git push origin $thebranch

# switch back to the original branch
git checkout $orig_branch
